library(ggplot2)
qplot(Wind,Temp,data=airquality,color=Month)
airquality$Month <- factor(airquality$Month)
qplot(Wind,Temp,data=airquality,color=I("red"))
qplot(Wind,Temp,data=airquality,size=Month)
qplot(Wind,Temp,data=airquality,shape=I(10),xlab="wind",ylab="temp",main="title")
qplot(Wind,Temp,data=airquality,geom=c("point","smooth"),color=Month)
qplot(Wind,Temp,data=airquality,facets = Month ~.)
qplot(Wind,Temp,data=airquality,facets = .~Month)
qplot(Wind,data=airquality,facets = Month ~.)
qplot(Wind,data=airquality,fill=Month)
qplot(Wind,data=airquality,geom="density")
qplot(Wind,data=airquality,geom="density",color=Month)
qplot(Wind,data=airquality,geom="dotplot")
