hist(airquality$Wind,xlab="wind")
boxplot(airquality$Wind,xlab="wind",ylab="speed(mph)")
boxplot(Wind~Month,airquality,xlab="Month",ylab="speed(mph)")
plot(airquality$Wind,airquality$Temp)
with(airquality,plot(Wind,Temp))
title(main="wind and Temp in NYC")
with(airquality,plot(Wind,Temp,type="n"))
with(subset(airquality,Month=9),points(Wind,Temp,col="red"))
with(subset(airquality,Month=5),points(Wind,Temp,col="blue"))
with(subset(airquality,Month %in% c(6,7,8)),points(Wind,Temp,col="black"))
fit <- lm(Temp ~ Wind,airquality)
abline(fit,lwd=2)
legend("topright",pch=1,col=c("red","blue","black"),legend = c("9","5","6、7、8"))
par("bg")
par("col")
par("mar")
par("mfrow")
par("mfcol")
?par
par(mfrow=c(1,2))
hist(airquality$Temp)
hist(airquality$Wind)
par(mfrow=c(1,1))
boxplot(airquality$Wind)
par(mfcol=c(2,1))
boxplot(airquality$Temp)
boxplot(airquality$Wind)
